version: 2

shared: &shared
  parallelism: 1
  working_directory: ~/app
  steps:
    - checkout

    - run: mix local.hex --force
    - run: mix local.rebar --force

    - restore_cache:
        keys:
          - v1-mix-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "mix.lock" }}
    - restore_cache:
        keys:
          - v1-build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
    - run: mix do deps.get, compile
    - save_cache:
        key: v1-mix-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "mix.lock" }}
        paths: "deps"
    - save_cache:
        key: v1-build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
        paths: "_build"

    - run: mix test

jobs:
  "elixir-1.5":
    docker:
      - image: circleci/elixir:1.5
        environment:
          MIX_ENV: test
      - image: rabbitmq:3.6-alpine

    <<: *shared

  "elixir-1.6":
    docker:
      - image: circleci/elixir:1.6
        environment:
          MIX_ENV: test
      - image: rabbitmq:3.6-alpine

    <<: *shared

workflows:
  version: 2
  build:
    jobs:
      - "elixir-1.5"
      - "elixir-1.6"
